json.id addiction_occurrence.user_id
json.location addiction_occurrence.location
json.circumstance addiction_occurrence.circumstance
json.amount addiction_occurrence.amount
json.cost addiction_occurrence.cost
json.craving addiction_occurrence.craving
json.addiction addiction_occurrence.addiction.name
