
User.create!([
  {name: "mike", email: "mike@gmail.com", password: "password", password_confirmation: "password"},
  {name: "joe", email: "joe@gmail.com", password: "password", password_confirmation: "password"},
  {name: "bob", email: "bob@gmail.com", password: "password", password_confirmation: "password"},
  {name: "Tim", email: "tim@gmail.com", password: "password", password_confirmation: "password"}
])

Addiction.create!([
  {name: "cookies"},
  {name: "Nicotine"},
  {name: "Alcohol"},
  {name: "Opioid"},
  {name: "twix"},
  {name: "hot chips"},
  {name: "phone"},
  {name: "Junk Food"},
  {name: "Caffeine"},
  {name: "anything"},
  {name: "add"},
  {name: "Peppermint"},
  {name: "Milk"},
  {name: "Marijuana"},
  {name: "Meth"},
  {name: "Heroin"},
  {name: "Cocaine"},
  {name: "Ecstasy"},
  {name: "Gambling"},
  {name: "Pills"},
  {name: "Pain Killers"},
  {name: "Nail Biting"},
  {name: "ice cream"},
  {name: "Pop"},
  {name: "Cake"}
])


AddictionOccurrence.create!([
  {user_id: 1, addiction_id: 1, location: "my-home", circumstance: "angry", amount: 4, cost: "2.0", craving: nil},
  {user_id: 2, addiction_id: 3, location: "restaurant", circumstance: "angry", amount: 1, cost: nil, craving: false},
  {user_id: 2, addiction_id: 3, location: "my-home", circumstance: "angry", amount: 1, cost: nil, craving: false},
  {user_id: 2, addiction_id: 2, location: "work", circumstance: "angry", amount: 3, cost: nil, craving: false},
  {user_id: 2, addiction_id: 2, location: "car", circumstance: "bored", amount: 2, cost: "2.0", craving: false},
  {user_id: 2, addiction_id: 2, location: "my-home", circumstance: "whatever", amount: 2, cost: "2.0", craving: true},
  {user_id: 3, addiction_id: 3, location: "work", circumstance: "depressed", amount: 1, cost: "2.0", craving: false},
  {user_id: 2, addiction_id: 2, location: nil, circumstance: "alone", amount: nil, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 65, location: "car", circumstance: "Hungry", amount: 2, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 1, location: "work", circumstance: "Meeting with Boss", amount: 2, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 7, location: "car", circumstance: "hanging with Jeff", amount: 1, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 2, location: "work", circumstance: "Office Party", amount: 3, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 11, location: "my-home", circumstance: "Out on a date", amount: 2, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 8, location: "car", circumstance: "Lonely", amount: 3, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 1, location: "my-home", circumstance: "alone", amount: 2, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 2, location: "bar", circumstance: "stressful morning", amount: 1, cost: nil, craving: nil},
  {user_id: 2, addiction_id: 47, location: "work", circumstance: "free doughnuts", amount: 3, cost: nil, craving: false},
  {user_id: 2, addiction_id: 8, location: "a-house", circumstance: "Hanging with Tim", amount: 1, cost: nil, craving: false},
  {user_id: 2, addiction_id: 9, location: "club", circumstance: "hanging with Susan", amount: 1, cost: nil, craving: true},
  {user_id: 2, addiction_id: 1, location: "work", circumstance: "lunch with Jeff", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 67, location: "my-home", circumstance: "Code freeze ", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "my-home", circumstance: "No alternatives?", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "my-home", circumstance: "No alternatives?", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "my-home", circumstance: "No alternatives?", amount: 2, cost: nil, craving: true},
  {user_id: 4, addiction_id: 69, location: "restaurant", circumstance: "B-Day Celebration", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "work", circumstance: "retirement party", amount: 2, cost: nil, craving: false},
  {user_id: 2, addiction_id: 1, location: "work", circumstance: "alone", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 67, location: "car", circumstance: "Studying", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "restaurant", circumstance: "bad waiter", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "a-house", circumstance: "Waiting", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "other", circumstance: "Prework Due", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "other", circumstance: "Algorithm", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "my-home", circumstance: "code complete", amount: 3, cost: nil, craving: true},
  {user_id: 4, addiction_id: 70, location: "my-home", circumstance: "break-up", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "work", circumstance: "New flavor", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "car", circumstance: "No alternatives?", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 68, location: "bar", circumstance: "avoid alchohol", amount: 2, cost: nil, craving: true},
  {user_id: 4, addiction_id: 68, location: "a-house", circumstance: "party", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 69, location: "restaurant", circumstance: "B-Day Celebration", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "work", circumstance: "party", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "car", circumstance: "No alternatives?", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "my-home", circumstance: "no meth", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "my-home", circumstance: "bored", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "my-home", circumstance: "no meth", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "other", circumstance: "capstone", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "other", circumstance: "stand-up", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "other", circumstance: "code review", amount: 1, cost: nil, craving: false},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no meth", amount: 1, cost: nil, craving: false},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no cocaine", amount: 3, cost: nil, craving: false},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no smack", amount: 1, cost: nil, craving: false},
  {user_id: 5, addiction_id: 67, location: "other", circumstance: "hungry", amount: 2, cost: nil, craving: false},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no cocaine", amount: 1, cost: nil, craving: true},
  {user_id: 5, addiction_id: 71, location: "restaurant", circumstance: "peer pressure", amount: 3, cost: nil, craving: false},
  {user_id: 5, addiction_id: 72, location: "work", circumstance: "stressed", amount: 3, cost: nil, craving: false},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no smack", amount: 1, cost: nil, craving: true},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no cocaine", amount: 1, cost: nil, craving: true},
  {user_id: 5, addiction_id: 1, location: "work", circumstance: "no meth", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 67, location: "other", circumstance: "bully ", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 67, location: "restaurant", circumstance: "bad waiter", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 68, location: "work", circumstance: "tried water", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 68, location: "club", circumstance: "party", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 68, location: "restaurant", circumstance: "tried water", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 68, location: "my-home", circumstance: "tried water", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 70, location: "work", circumstance: "no meth", amount: 1, cost: nil, craving: true},
  {user_id: 2, addiction_id: 3, location: "restaurant", circumstance: "sad", amount: 1, cost: nil, craving: nil},
  {user_id: 4, addiction_id: 68, location: "my-home", circumstance: "New flavor", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 70, location: "restaurant", circumstance: "break-up", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 73, location: "my-home", circumstance: "hungry", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "my-home", circumstance: "no meth", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "my-home", circumstance: "retirement party", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "restaurant", circumstance: "break-up", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "other", circumstance: "tried water", amount: 2, cost: nil, craving: true},
  {user_id: 4, addiction_id: 70, location: "work", circumstance: "break-up", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "car", circumstance: "custom", amount: 3, cost: nil, craving: true},
  {user_id: 4, addiction_id: 70, location: "my-home", circumstance: "code complete", amount: 3, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "car", circumstance: "nervous", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 67, location: "work", circumstance: "nervous", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 7, location: "my-home", circumstance: "nervous", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 70, location: "other", circumstance: "retirement party", amount: 1, cost: nil, craving: true},
  {user_id: 4, addiction_id: 7, location: "car", circumstance: "nervous", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 1, location: "work", circumstance: "Argument", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 77, location: "my-home", circumstance: "Breath", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "club", circumstance: "avoid alchohol", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "a-house", circumstance: "New flavor", amount: 2, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "car", circumstance: "avoid alchohol", amount: 1, cost: nil, craving: false},
  {user_id: 4, addiction_id: 68, location: "my-home", circumstance: "party", amount: 2, cost: nil, craving: false}
])
Circumstance.create!([
  {description: "Hanging with Paul"}
])
